Zuev HW1
h31/NetworksLab2020HSE pull request #1
Opened 2020-04-18 21:18 UTC by zuevmaxim

2020-05-21 02:24 UTC, h31 requested changes

2020-05-21 02:24 UTC, h31 commented on tcp/README.md
> +A(8 байт) - метка времени std::time_t
Как правило, в time_t хранится так называемый Unix time (или Epoch time). Возможно, ваш протокол будет читать человек, который не знает C++, поэтому стоит использовать кросс-языковые термины в описании. Плюс, конкретный формат хранения time_t жестко не зафиксирован в спецификации C++ STL, что не очень хорошо для обеспечения совместимости между машинами.

2020-05-21 02:24 UTC, h31 commented on tcp/README.md
> +C(значение B байт) - имя отправителя
Для текста нужно указать кодировку и наличие нулевого байта в конце

2020-05-21 02:24 UTC, h31 commented on tcp/ioutils.h
> +        if (x <= 0) return -1;
Не очень хорошо, что мы не различаем корректное и некорректное закрытие сокета (FIN и RST соответственно)

2020-05-21 02:24 UTC, h31 commented on tcp/server/Server.cpp
> +    listen(m_sockFD, maxClientsNumber);
Для чего у вас используется переменная `maxClientsNumber`?

2020-05-21 02:24 UTC, h31 commented on tcp/serialization.h
> +T intFromArray(const char (& bytes)[N]) {
Вместо копирования можно кастовать массив к указателю на нужный тип данных (не забывая про byte order). Это не принципиальный момент, просто другой вариант решения.

2020-05-21 02:24 UTC, h31 commented on tcp/server/main.cpp
> +    uint16_t port = atoi(argv[1]);
Желательно использовать более безопасные варианты, например, std::stoi

2020-05-21 02:31 UTC, h31 commented on tcp/client/Client.cpp
> +void Client::read_routine() {
Функция довольно сложная, для того, чтобы она проще читалась, можно разбить её на несколько функций

2020-05-30 21:03 UTC, zuevmaxim commented on tcp/server/Server.cpp
> +    listen(m_sockFD, maxClientsNumber);
Интерфейс функции listen требует ограничение на максимальное число клиентов, ожидающих соединение. Здесь этот парамерт вынесен в конструктор Server.

2020-05-30 21:04 UTC, zuevmaxim commented on tcp/serialization.h
> +T intFromArray(const char (& bytes)[N]) {
Я так понял, что исправлять это не обязательно. Тем более я не понимаю, как обойтись без копирования, если порядок байт не тот.

2020-07-18 06:00 UTC, closed without merging